Fix for issue 19: add Unicode to Worknik word list
Trying to add a Unicode to a Wordnik list causes an `AttributeError: 'unicode' object has no attribute '__dict__'`.

Here's a fix. 

Tests are in issue 19. They fail before the fix, and pass after the fix.